Repository GlobeMC/crashmc.com, pull requests merged in 2023-08, with the labels that each got.

#91 添加详细规则
  .github/ISSUE_TEMPLATE/CRASH-UPLOAD.yml
  components/analyzer.vue
  docs/analyzer.md
Labels: Bug, Feature

#87 ✨ feature: restruct docs
  docs/.vitepress/config.ts
  docs/basis.md
  docs/client/index.md
  docs/client/mods.md
  docs/client/system.md
  docs/client/vanilla.md
  docs/clients.md
  docs/index.md
  docs/server/hybrid.md
  docs/server/index.md
  docs/server/mods.md
  docs/server/plugins.md
  docs/server/shared.md
  docs/server/vanilla.md
  docs/servers.md
Labels: Doc

#92 ✨ feat(theme): add author
  docs/.vitepress/theme/components/Author.vue
  docs/.vitepress/theme/index.ts
  docs/basis.md
Labels: Feature
